name: SimpleVaultPro
version: 3.0
main: me.simplevault.SimpleVaultPro
api-version: 1.21

commands:
  kho:
    description: Mo kho
    usage: /kho
    permission: kho.use

permissions:
  kho.use:
    default: true
